#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# ADMIN_USER	Initial LimeSurvey Admin User
# ADMIN_NAME	Initial LimeSurvey Admin Username
# ADMIN_EMAIL	Initial LimeSurvey Admin Email
# ADMIN_PASSWORD	Initial LimeSurvey Admin Password
# PUBLIC_URL	Public URL for public scripts
# BASE_URL	Application Base URL

host = data.get('host')

ADMIN_USER = data.get('ADMIN_USER', 'admin')
ADMIN_NAME = data.get('ADMIN_NAME', 'Admin')
ADMIN_EMAIL = data.get('ADMIN_EMAIL', 'admin@admin.com')
ADMIN_PASSWORD = data.get('ADMIN_PASSWORD', 'password')
PUBLIC_URL = 'https://'+host
BASE_URL = 'https://'+host

limesurvey_env = {
    'ADMIN_USER': ADMIN_USER,
    'ADMIN_NAME': ADMIN_NAME,
    'ADMIN_EMAIL': ADMIN_EMAIL,
    'ADMIN_PASSWORD': ADMIN_PASSWORD,
    'PUBLIC_URL': PUBLIC_URL,
    'BASE_URL': BASE_URL
}

agent.write_envfile("limesurvey.env", limesurvey_env)

#agent.dump_env()
