#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

if os.path.exists("limesurvey.env"):
    data = agent.read_envfile("limesurvey.env")
    config["ADMIN_USER"] = data["ADMIN_USER"]
    config["ADMIN_NAME"] = data["ADMIN_NAME"]
    config["ADMIN_EMAIL"] = data["ADMIN_EMAIL"]
    config["ADMIN_PASSWORD"] = data["ADMIN_PASSWORD"]
    config["PUBLIC_URL"] = data["PUBLIC_URL"]
    config["BASE_URL"] = data["BASE_URL"]
else:
    config["ADMIN_USER"] = ""
    config["ADMIN_NAME"] = ""
    config["ADMIN_EMAIL"] = ""
    config["ADMIN_PASSWORD"] = ""
    config["PUBLIC_URL"] = ""
    config["BASE_URL"] = ""
# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
